// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/topics/ticket.proto

package topics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_proto_topics_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_topics_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_proto_topics_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ticket) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Ticket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_topics_ticket_proto protoreflect.FileDescriptor

const file_proto_topics_ticket_proto_rawDesc = "" +
	"\n" +
	"\x19proto/topics/ticket.proto\x12\rtopics.ticket\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB7Z5github.com/iamnotrodger/golang-kafka/pkg/proto/topicsb\x06proto3"

var (
	file_proto_topics_ticket_proto_rawDescOnce sync.Once
	file_proto_topics_ticket_proto_rawDescData []byte
)

func file_proto_topics_ticket_proto_rawDescGZIP() []byte {
	file_proto_topics_ticket_proto_rawDescOnce.Do(func() {
		file_proto_topics_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_topics_ticket_proto_rawDesc), len(file_proto_topics_ticket_proto_rawDesc)))
	})
	return file_proto_topics_ticket_proto_rawDescData
}

var file_proto_topics_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_topics_ticket_proto_goTypes = []any{
	(*Ticket)(nil),                // 0: topics.ticket.Ticket
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_topics_ticket_proto_depIdxs = []int32{
	1, // 0: topics.ticket.Ticket.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_topics_ticket_proto_init() }
func file_proto_topics_ticket_proto_init() {
	if File_proto_topics_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_topics_ticket_proto_rawDesc), len(file_proto_topics_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_topics_ticket_proto_goTypes,
		DependencyIndexes: file_proto_topics_ticket_proto_depIdxs,
		MessageInfos:      file_proto_topics_ticket_proto_msgTypes,
	}.Build()
	File_proto_topics_ticket_proto = out.File
	file_proto_topics_ticket_proto_goTypes = nil
	file_proto_topics_ticket_proto_depIdxs = nil
}
